name: Docker Image CI

on:
  push:
    branches: [ dev ]


jobs:
  build:
    # build and push to docker
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v1
    -
      name: Dockerhub login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
    -
      name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    -
      name: Build dockerfile (with push)
      run: |
                docker buildx build \
                --platform=linux/arm/v7,linux/arm64 \
                --output "type=image,push=true" \
                --file ./Dockerfile . \
                --tag blots/tilcev2:dev
