name: Deploy to production

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    runs-on: self-hosted
    environment: tillicev2
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      -
        name: update dependencies
        run: npm i
      -
        name: Start server
        run: env $( echo "${{secrets.ENVVARS}}" | xargs) pm2 start tillv2
